import openpyxl
from openpyxl.utils import column_index_from_string

template_path = "offer-template.xlsx"
output_path = "items_output_2.xlsx"  

wb = openpyxl.load_workbook(template_path)
ws = wb.worksheets[1] 

# JSON de entrada
input_json = [
    {
        "item": 1,
        "valve type": "ball valve",
        "end_user": "ARAMCO",
        "9COM": 6000000250,
        "size": "6\"",
        "class": "300#",
        "operation": "Manual",
        "body_construction": "SPLIT BODY",
        "ball_construction": "TRUNNION",
        "bore": "FULL BORE",
        "ends": "FLANGED RAISED FACE",
        "standard": "ISO",
        "tag": "N/A",
        "model": "TSB",
        "body": "ASTM A216 WCC",
        "ball": "ASTM A351 CF8M",
        "stem": "ASTM A276 316",
        "seat_housing": "ASTM A182 F316",
        "seat": "PTFE MOD + RCAR",
        "seals": "VITON O-RINGS + GRAPHITE SEALS",
        "injectors": "Injector1",
        "drain_vent": "GATE VALVES ON DRAIN & VENT ACC. ARAMCO SPECS",
        "painting": "CS VALVES PAINTED ACC. PROJECT SPECS",
        "temperature": "-20 ºC / 180 ºC",
        "service": "HYDROCARBON",
        "available": "Yes"
    },
    {
        "item": 2,
        "valve type": "ball valve",
        "end_user": "ARAMCO",
        "9COM": 6000000240,
        "size": "1\"",
        "class": "150#",
        "operation": "PNEUMATIC",
        "body_construction": "SPLIT BODY",
        "ball_construction": "Metal",
        "bore": "FULL BORE",
        "ends": "Flanged",
        "standard": "ANSI",
        "tag": "060-ZV-11140",
        "model": "FB",
        "body": "ASTM A182 F316/F316L",
        "ball": "Ball2",
        "stem": "Stem2",
        "seat_housing": "Housing2",
        "seat": "Seat2",
        "seals": "Seal2",
        "injectors": "Injector2",
        "drain_vent": "Vent2",
        "painting": "Paint2",
        "temperature": "25C",
        "service": "Service2",
        "available": "No"
    },
    {
        "item": 3,
        "valve type": "gate valve",
        "end_user": "SABIC",
        "9COM": "N/A",
        "size": "12\"",
        "class": "600#",
        "operation": "Manual",
        "body_construction": "CAST BODY",
        "ball_construction": "TRUNNION",
        "bore": "REDUCED BORE",
        "ends": "BUTT WELD",
        "standard": "API 600",
        "tag": "110-GV-101",
        "model": "GV-S12",
        "body": "ASTM A216 WCC",
        "ball": "ASTM A105",
        "stem": "ASTM A276 304",
        "seat_housing": "ASTM A182 F304",
        "seat": "PEEK",
        "seals": "GRAPHITE",
        "injectors": "N/A",
        "drain_vent": "N/A",
        "painting": "CS VALVES PAINTED ACC. PROJECT SPECS",
        "temperature": "-40 ºC / 250 ºC",
        "service": "STEAM",
        "available": "Yes"
    },
    {
        "item": 4,
        "valve type": "globe valve",
        "end_user": "ARAMCO",
        "9COM": 6000000239,
        "size": "2\"",
        "class": "150#",
        "operation": "Electric Actuated",
        "body_construction": "SINGLE BODY",
        "ball_construction": "Floating",
        "bore": "FULL BORE",
        "ends": "THREADED",
        "standard": "ISO 17292",
        "tag": "080-GV-101",
        "model": "GV-S02",
        "body": "ASTM A351 CF8",
        "ball": "ASTM A351 CF3",
        "stem": "ASTM A276 316",
        "seat_housing": "ASTM A182 F316",
        "seat": "RPTFE",
        "seals": "VITON",
        "injectors": "Injector3",
        "drain_vent": "Ball Drain",
        "painting": "NOT PAINTED",
        "temperature": "-10 ºC / 120 ºC",
        "service": "WATER",
        "available": "No"
    },
    {
        "item": 5,
        "valve type": "check valve",
        "end_user": "TOTAL",
        "9COM": "N/A",
        "size": "10\"",
        "class": "150#",
        "operation": "Manual",
        "body_construction": "CAST BODY",
        "ball_construction": "N/A",
        "bore": "REDUCED BORE",
        "ends": "FLANGED",
        "standard": "ISO 17292",
        "tag": "CV-002",
        "model": "CV-150",
        "body": "ASTM A216 WCB",
        "ball": "N/A",
        "stem": "N/A",
        "seat_housing": "N/A",
        "seat": "PTFE",
        "seals": "VITON",
        "injectors": "N/A",
        "drain_vent": "N/A",
        "painting": "CS VALVES PAINTED ACC. PROJECT SPECS",
        "temperature": "0 ºC / 100 ºC",
        "service": "WATER",
        "available": "Yes"
    },
    {
        "item": 6,
        "valve type": "ball valve",
        "end_user": "SHELL",
        "9COM": "N/A",
        "size": "4\"",
        "class": "300#",
        "operation": "Hydraulic",
        "body_construction": "SPLIT BODY",
        "ball_construction": "Floating",
        "bore": "FULL BORE",
        "ends": "BUTT WELD",
        "standard": "ISO 17292",
        "tag": "045-ZV-301",
        "model": "AP-300",
        "body": "ASTM A182 F316",
        "ball": "ASTM A351 CF3M",
        "stem": "ASTM A276 316",
        "seat_housing": "ASTM A182 F316",
        "seat": "RPTFE",
        "seals": "GRAPHITE",
        "injectors": "Injector4",
        "drain_vent": "Drain Valve",
        "painting": "NOT PAINTED",
        "temperature": "-30 ºC / 220 ºC",
        "service": "GAS",
        "available": "Yes"
    },
    {
        "item": 7,
        "valve type": "butterfly valve",
        "end_user": "BP",
        "9COM": "N/A",
        "size": "8\"",
        "class": "150#",
        "operation": "PNEUMATIC",
        "body_construction": "SINGLE BODY",
        "ball_construction": "N/A",
        "bore": "FULL BORE",
        "ends": "LUGGED",
        "standard": "ISO 5752",
        "tag": "070-BV-502",
        "model": "BV-150",
        "body": "ASTM A536 65-45-12",
        "ball": "N/A",
        "stem": "ASTM A182 F6A",
        "seat_housing": "N/A",
        "seat": "EPDM",
        "seals": "N/A",
        "injectors": "N/A",
        "drain_vent": "N/A",
        "painting": "PAINTED AS PER SPEC",
        "temperature": "-10 ºC / 80 ºC",
        "service": "AIR",
        "available": "Yes"
    },
    {
        "item": 8,
        "valve type": "gate valve",
        "end_user": "CHEVRON",
        "9COM": "N/A",
        "size": "16\"",
        "class": "600#",
        "operation": "Electric Actuated",
        "body_construction": "CAST BODY",
        "ball_construction": "TRUNNION",
        "bore": "REDUCED BORE",
        "ends": "BUTT WELD",
        "standard": "API 600",
        "tag": "GV-5016",
        "model": "GV-600",
        "body": "ASTM A216 WCC",
        "ball": "ASTM A105",
        "stem": "ASTM A182 F6A",
        "seat_housing": "ASTM A182 F304",
        "seat": "PEEK",
        "seals": "GRAPHITE",
        "injectors": "N/A",
        "drain_vent": "N/A",
        "painting": "PAINTED AS PER SPEC",
        "temperature": "-50 ºC / 250 ºC",
        "service": "CRUDE OIL",
        "available": "Yes"
    },
    {
        "item": 9,
        "valve type": "check valve",
        "end_user": "EXXON",
        "9COM": "N/A",
        "size": "2\"",
        "class": "150#",
        "operation": "Manual",
        "body_construction": "CAST BODY",
        "ball_construction": "N/A",
        "bore": "FULL BORE",
        "ends": "THREADED",
        "standard": "API 6D",
        "tag": "CV-1502",
        "model": "CV-API6D",
        "body": "ASTM A216 WCC",
        "ball": "N/A",
        "stem": "N/A",
        "seat_housing": "N/A",
        "seat": "PTFE",
        "seals": "VITON",
        "injectors": "N/A",
        "drain_vent": "N/A",
        "painting": "PAINTED AS PER SPEC",
        "temperature": "-10 ºC / 120 ºC",
        "service": "WATER",
        "available": "Yes"
    },
    {
        "item": 10,
        "valve type": "plug valve",
        "end_user": "PETROBRAS",
        "9COM": "N/A",
        "size": "6\"",
        "class": "300#",
        "operation": "Manual",
        "body_construction": "SPLIT BODY",
        "ball_construction": "N/A",
        "bore": "REDUCED BORE",
        "ends": "FLANGED",
        "standard": "API 6D",
        "tag": "PV-06300",
        "model": "PV-300",
        "body": "ASTM A216 WCC",
        "ball": "N/A",
        "stem": "ASTM A182 F6A",
        "seat_housing": "N/A",
        "seat": "PTFE",
        "seals": "GRAPHITE",
        "injectors": "N/A",
        "drain_vent": "N/A",
        "painting": "PAINTED AS PER SPEC",
        "temperature": "-40 ºC / 180 ºC",
        "service": "OIL",
        "available": "Yes"
    },
    {
        "item": 11,
        "valve type": "ball valve",
        "end_user": "ARAMCO",
        "9COM": 6000000210,
        "size": "3\"",
        "class": "150#",
        "operation": "Manual",
        "body_construction": "SPLIT BODY",
        "ball_construction": "Floating",
        "bore": "FULL BORE",
        "ends": "THREADED",
        "standard": "API 6D",
        "tag": "BV-03150",
        "model": "BV-150",
        "body": "ASTM A105",
        "ball": "ASTM A182 F316",
        "stem": "ASTM A182 F6A",
        "seat_housing": "ASTM A105",
        "seat": "PTFE",
        "seals": "GRAPHITE",
        "injectors": "N/A",
        "drain_vent": "Ball Valve",
        "painting": "PAINTED AS PER SPEC",
        "temperature": "-29 ºC / 200 ºC",
        "service": "GAS",
        "available": "Yes"
    },
    {
        "item": 12,
        "valve type": "butterfly valve",
        "end_user": "BP",
        "9COM": 6000000220,
        "size": "12\"",
        "class": "150#",
        "operation": "Pneumatic",
        "body_construction": "SINGLE BODY",
        "ball_construction": "N/A",
        "bore": "FULL BORE",
        "ends": "Wafer",
        "standard": "ISO 5752",
        "tag": "BV-12350",
        "model": "BV-150",
        "body": "ASTM A216 WCC",
        "ball": "N/A",
        "stem": "ASTM A182 F316",
        "seat_housing": "N/A",
        "seat": "EPDM",
        "seals": "N/A",
        "injectors": "N/A",
        "drain_vent": "N/A",
        "painting": "PAINTED AS PER SPEC",
        "temperature": "-20 ºC / 100 ºC",
        "service": "WATER",
        "available": "Yes"
    },
    {
        "item": 13,
        "valve type": "gate valve",
        "end_user": "SHELL",
        "9COM": 6000000235,
        "size": "18\"",
        "class": "300#",
        "operation": "Electric Actuated",
        "body_construction": "CAST BODY",
        "ball_construction": "TRUNNION",
        "bore": "FULL BORE",
        "ends": "FLANGED",
        "standard": "API 600",
        "tag": "GV-18300",
        "model": "GV-300",
        "body": "ASTM A105",
        "ball": "ASTM A182 F6A",
        "stem": "ASTM A276 316",
        "seat_housing": "ASTM A182 F316",
        "seat": "PTFE",
        "seals": "GRAPHITE",
        "injectors": "N/A",
        "drain_vent": "Drain Valve",
        "painting": "PAINTED AS PER SPEC",
        "temperature": "-40 ºC / 250 ºC",
        "service": "HYDROCARBON",
        "available": "No"
    },
    {
        "item": 14,
        "valve type": "ball valve",
        "end_user": "TOTAL",
        "9COM": 6000000245,
        "size": "2\"",
        "class": "600#",
        "operation": "Hydraulic",
        "body_construction": "SPLIT BODY",
        "ball_construction": "Floating",
        "bore": "FULL BORE",
        "ends": "FLANGED",
        "standard": "API 6D",
        "tag": "BV-02600",
        "model": "BV-600",
        "body": "ASTM A105",
        "ball": "ASTM A182 F316",
        "stem": "ASTM A276 316",
        "seat_housing": "ASTM A105",
        "seat": "RPTFE",
        "seals": "GRAPHITE",
        "injectors": "N/A",
        "drain_vent": "N/A",
        "painting": "PAINTED AS PER SPEC",
        "temperature": "-29 ºC / 200 ºC",
        "service": "OIL",
        "available": "Yes"
    },
    {
        "item": 15,
        "valve type": "butterfly valve",
        "end_user": "EXXON",
        "9COM": 6000000251,
        "size": "6\"",
        "class": "300#",
        "operation": "Manual",
        "body_construction": "SINGLE BODY",
        "ball_construction": "N/A",
        "bore": "FULL BORE",
        "ends": "Wafer",
        "standard": "ISO 5752",
        "tag": "BV-06300",
        "model": "BV-300",
        "body": "ASTM A536",
        "ball": "N/A",
        "stem": "ASTM A182 F316",
        "seat_housing": "N/A",
        "seat": "EPDM",
        "seals": "N/A",
        "injectors": "N/A",
        "drain_vent": "N/A",
        "painting": "PAINTED AS PER SPEC",
        "temperature": "-10 ºC / 80 ºC",
        "service": "GAS",
        "available": "Yes"
    },
    {
        "item": 16,
        "valve type": "gate valve",
        "end_user": "PETROBRAS",
        "9COM": 6000000260,
        "size": "14\"",
        "class": "600#",
        "operation": "Pneumatic",
        "body_construction": "CAST BODY",
        "ball_construction": "TRUNNION",
        "bore": "REDUCED BORE",
        "ends": "BUTT WELD",
        "standard": "API 600",
        "tag": "GV-14600",
        "model": "GV-600",
        "body": "ASTM A216 WCC",
        "ball": "ASTM A182 F6A",
        "stem": "ASTM A276 316",
        "seat_housing": "ASTM A182 F316",
        "seat": "PTFE",
        "seals": "GRAPHITE",
        "injectors": "N/A",
        "drain_vent": "N/A",
        "painting": "PAINTED AS PER SPEC",
        "temperature": "-40 ºC / 250 ºC",
        "service": "CRUDE OIL",
        "available": "No"
    },
    {
        "item": 17,
        "valve type": "ball valve",
        "end_user": "SABIC",
        "9COM": 6000000270,
        "size": "10\"",
        "class": "300#",
        "operation": "Electric Actuated",
        "body_construction": "SPLIT BODY",
        "ball_construction": "TRUNNION",
        "bore": "FULL BORE",
        "ends": "FLANGED",
        "standard": "API 6D",
        "tag": "BV-10300",
        "model": "BV-300",
        "body": "ASTM A105",
        "ball": "ASTM A182 F316",
        "stem": "ASTM A276 316",
        "seat_housing": "ASTM A105",
        "seat": "RPTFE",
        "seals": "GRAPHITE",
        "injectors": "N/A",
        "drain_vent": "Drain Valve",
        "painting": "PAINTED AS PER SPEC",
        "temperature": "-29 ºC / 200 ºC",
        "service": "OIL",
        "available": "Yes"
    },
    {
        "item": 18,
        "valve type": "butterfly valve",
        "end_user": "SHELL",
        "9COM": 6000000280,
        "size": "20\"",
        "class": "150#",
        "operation": "Hydraulic",
        "body_construction": "SINGLE BODY",
        "ball_construction": "N/A",
        "bore": "FULL BORE",
        "ends": "Wafer",
        "standard": "ISO 5752",
        "tag": "BV-20150",
        "model": "BV-150",
        "body": "ASTM A536",
        "ball": "N/A",
        "stem": "ASTM A182 F316",
        "seat_housing": "N/A",
        "seat": "EPDM",
        "seals": "N/A",
        "injectors": "N/A",
        "drain_vent": "N/A",
        "painting": "PAINTED AS PER SPEC",
        "temperature": "-20 ºC / 80 ºC",
        "service": "WATER",
        "available": "Yes"
    },
    {
        "item": 19,
        "valve type": "check valve",
        "end_user": "ARAMCO",
        "9COM": 6000000290,
        "size": "3\"",
        "class": "600#",
        "operation": "Manual",
        "body_construction": "CAST BODY",
        "ball_construction": "N/A",
        "bore": "FULL BORE",
        "ends": "THREADED",
        "standard": "API 6D",
        "tag": "CV-03600",
        "model": "CV-600",
        "body": "ASTM A105",
        "ball": "N/A",
        "stem": "N/A",
        "seat_housing": "N/A",
        "seat": "PTFE",
        "seals": "VITON",
        "injectors": "N/A",
        "drain_vent": "N/A",
        "painting": "PAINTED AS PER SPEC",
        "temperature": "-29 ºC / 200 ºC",
        "service": "GAS",
        "available": "Yes"
    },
    {
        "item": 20,
        "valve type": "plug valve",
        "end_user": "TOTAL",
        "9COM": 6000000300,
        "size": "8\"",
        "class": "150#",
        "operation": "Pneumatic",
        "body_construction": "SPLIT BODY",
        "ball_construction": "N/A",
        "bore": "REDUCED BORE",
        "ends": "FLANGED",
        "standard": "API 6D",
        "tag": "PV-08150",
        "model": "PV-150",
        "body": "ASTM A105",
        "ball": "N/A",
        "stem": "ASTM A182 F6A",
        "seat_housing": "N/A",
        "seat": "PTFE",
        "seals": "GRAPHITE",
        "injectors": "N/A",
        "drain_vent": "N/A",
        "painting": "PAINTED AS PER SPEC",
        "temperature": "-40 ºC / 180 ºC",
        "service": "OIL",
        "available": "Yes"
    }
]


items_to_excel = {
    "valve type": column_index_from_string("E"),
    "end_user": column_index_from_string("D"),
    "9COM": column_index_from_string("J"),
    "size": column_index_from_string("K"),
    "class": column_index_from_string("L"),
    "operation": column_index_from_string("F"),
    "body_construction": column_index_from_string("M"),
    "ball_construction": column_index_from_string("N"),
    "bore": column_index_from_string("O"),
    "ends": column_index_from_string("P"),
    "standard": column_index_from_string("Q"),
    "tag": column_index_from_string("G"),
    "model": column_index_from_string("R"),
    "body": column_index_from_string("S"),
    "ball": column_index_from_string("T"),
    "stem": column_index_from_string("U"),
    "seat_housing": column_index_from_string("V"),
    "seat": column_index_from_string("W"),
    "seals": column_index_from_string("X"),
    "injectors": column_index_from_string("Y"),
    "drain_vent": column_index_from_string("Z"),
    "painting": column_index_from_string("AA"),
    "temperature": column_index_from_string("AB"),
    "service": column_index_from_string("AC"),
    "available": column_index_from_string("AS")
}

starting_row = 9  
for index, item in enumerate(input_json, start=0):

    ws.cell(row=starting_row + index, column=2, value=item["item"])
    

    for attribute, col_index in items_to_excel.items():

        value = item.get(attribute, "N/A")
        

        ws.cell(row=starting_row + index, column=col_index, value=value)


wb.save(output_path)

print(f"Arxiu Excel Creat: {output_path}")
